# Generated by Django 4.1 on 2023-04-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
