# Generated by Django 4.1 on 2023-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_authuser_password_remove_authuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='type',
            field=models.SmallIntegerField(null=True),
        ),
    ]
