# Generated by Django 4.1 on 2023-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_student_route_from_alter_student_route_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='apply',
            field=models.BooleanField(default=False),
        ),
    ]
