# Generated by Django 4.1 on 2023-04-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_student_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='home.college'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='home.manager'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pass',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='home.student'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
