# Generated by Django 4.1 on 2023-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_student_verify_college_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verify_manager_reject',
            field=models.BooleanField(default=False),
        ),
    ]
